### ISSUE TITLE
Add heatmap view of posterior probablitity results

### ISSUE THREAD

**Issue by a8wright** [OICR/PGMLab#14]
In particular I am interested in using this http://openscreen.cz/software/inchlib/home/ heatmap library for displaying the nodes. 

In the positions where the model shows the chemical structure I think we should show a ribbon structure. http://www.rcsb.org/pdb/images/5hou_bio_r_250.jpg?getBest=true

http://www.rcsb.org/pdb/gene/ABI1?evtc=Suggest&evta=GeneView&evtl=autosearch_SearchBar_querySuggest

**Comment by mdpham** [comment]
Added InCHlib js library for heatmap componnet and server-side data formatting
