### ISSUE TITLE
SQLite IntegrityError on initial Task insert and commit

### ISSUE THREAD

**Issue by mdpham** [OICR/PGMLab#30]
On initial insert of a Task (i.e. `session.add(Task)`) and commit, SQLite throws
`IntegrityError('(_sqlite3.IntegrityError) UNIQUE constraint failed: tasks.task_id')`

Subsequent inserts/updates throw:
`InvalidRequestError("This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_sqlite3.IntegrityError) UNIQUE constraint failed: tasks.task_id <...sql parameters...>)`

**Comment by a8wright** [comment]
This is complete

**Comment by a8wright** [comment]
Added database session management class to handle connection to Sqlite.
